TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 0.03
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.03

  acc_lim_theta: 0.6
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

  holonomic_robot: false

  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05

  
