obstacle_range: 2.5  #最大障碍物检测范围
raytrace_range: 3.0. #检测自由空间的最大范围
footprint: [[0.28, 0.28], [0.28, -0.28], [-0.28, 0.28], [-0.28, -0.28]] #机器人为矩形，设置机器的在坐标系内所占用的面积
inflation_radius: 0.55 #与障碍物的安全系数

observation_sources: laser_scan_sensor #只关注激光雷达的数据

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true} #设定激光雷达的相关参数
