local_costmap:
 global_frame: odom #指定本地代价地图参考系为odom
 robot_base_frame: base_link #指定机器人的base_frame为base_link
 update_frequency: 5.0 #指定地图更新频率
 publish_frequency: 2.0 #代价地图发布可视化信息的频率
 static_map: false #本地代价地图会不断的更新地图，所以这里设置为false
 rolling_window: true #设置滚动窗口，使得机器人始终在窗体中心位置
 width: 4.0 #代价地图的宽度
 height: 6.0 #代价地图的长度
 resolution: 0.05 #代价地图的分辨率
